# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Art',
        ),
    ]
